### ISSUE TITLE
Delay and times

### ISSUE THREAD

**Issue by Djacksonspears** [pshtif/Dash#10]
When my monitor resolution is set to 4k the delays and times don't seem to be right. I change it to 1080p and it fixes it.

**Comment by pshtif** [comment]
I am afraid I would need more info on this. I tried on 4k monitor and it works as expected. There is no dependency on a resolution of the monitor that sounds weird especially if the error seems to be time based not position based.

**Comment by pshtif** [comment]
I reached out to other people using Dash if they encountered such issue and no one has yet. Could you be more specific or send a minimal example?

**Comment by Djacksonspears** [comment]
> I reached out to other people using Dash if they encountered such issue and no one has yet. Could you be more specific or send a minimal example?

Yes. Sorry been working on other systems in the meantime. I will send you a video of an example ASAP.

**Comment by Djacksonspears** [comment]
Do you have a discord for dash so users can ask you questions?

**Comment by Djacksonspears** [comment]
[Desktop 2021.05.19 - 20.03.24.02.zip](https://github.com/pshtif/Dash/files/6535839/Desktop.2021.05.19.-.20.03.24.02.zip)

**Comment by Djacksonspears** [comment]
> [Desktop 2021.05.19 - 20.03.24.02.zip](https://github.com/pshtif/Dash/files/6535839/Desktop.2021.05.19.-.20.03.24.02.zip)

i attached a video i set the delay to 50s on the animation just to show. ignore the errors and warning they are from some other ecs systems running in the default world so nothing to do with this scene.

**Comment by Djacksonspears** [comment]
[video example 2.zip](https://github.com/pshtif/Dash/files/6536208/video.example.2.zip)

**Comment by Djacksonspears** [comment]
[Video Example 2 of Delay.zip](https://github.com/pshtif/Dash/files/6536221/Video.Example.2.of.Delay.zip)

**Comment by pshtif** [comment]
Hi I checked it out and can't simulate the issue. The only way this could happen is if you set Time.timeScale somewhere to a higher value so the 50s would be actually less. Otherwise the time calculation is pretty much standard using Time.deltaTime

Anyway good idea for a Dash setting to enable/disable using scaled time.

**Comment by Djacksonspears** [comment]
> Hi I checked it out and can't simulate the issue. The only way this could happen is if you set Time.timeScale somewhere to a higher value so the 50s would be actually less. Otherwise the time calculation is pretty much standard using Time.deltaTime
> 
> Anyway good idea for a Dash setting to enable/disable using scaled time.

Good assumption. But I am not using timeScale anywhere in our project. And the rest of our game uses Time.deltaTime in multiple different situations and the time is correct...

**Comment by Djacksonspears** [comment]
> > Hi I checked it out and can't simulate the issue. The only way this could happen is if you set Time.timeScale somewhere to a higher value so the 50s would be actually less. Otherwise the time calculation is pretty much standard using Time.deltaTime
> > Anyway good idea for a Dash setting to enable/disable using scaled time.
> 
> Good assumption. But I am not using timeScale anywhere in our project. And the rest of our game uses Time.deltaTime in multiple different situations and the time is correct...

Also I should mention, one time I open our project and use dash and it works perfect. Other times it doesn't without change. Could be a unity issue. Not sure though.
